import React from "react";
import type {Metadata} from "next";
import "@styles/globals.scss";
import Header from "@components/layout/header/header";
import {WindowWidthProvider} from '@hooks/UseWidth';
import Footer from "@components/layout/footer/footer";
import AgeWarningModal from "@components/modals/ageWarning/ageWarning";
import BookingModal from "@components/modals/booking/bookingModal";
import DevelopmentModal from "@components/modals/development/developmentModal";
import WrapperPreloader from "@components/layout/preloader/wrapperPreloader";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>
        <WindowWidthProvider>
            <WrapperPreloader/>
            <DevelopmentModal/>
            <AgeWarningModal/>
            <BookingModal/>
            <Header/>
            {children}
            <Footer/>
        </WindowWidthProvider>
        </body>
        </html>
    );
}
