export * as generalDataAPI from './routes/generalData';
export * as menuAPI from './routes/menu';
export * as articlesAPI from './routes/articles';
export * as partnersAPI from './routes/partners';
export * as tastesAPI from './routes/tastes';
export * as categoriesTobaccoAPI from './routes/categoriesTobacco';
export * as roomsAPI from './routes/rooms';
export * as orderAPI from './routes/order';
export * as galleryAPI from './routes/gallery';
